name: Npm Publish

on:
  workflow_call:
    inputs:
      runner:
        description: 'Runner to run the workflow on'
        required: false
        default: 'ubuntu-latest'
        type: string

jobs:
  test:
    name: Npm Publish
    runs-on: ${{ inputs.runner || 'ubuntu-latest'}}
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node & Install dependencies
        uses: stetind/web-github-composite-actions/setup-node-npm-action@v1

      - name: Print Environment Info
        run: npx nx report
        shell: bash

#      - name: Publish packages
#        run: npx nx release publish
#        shell: bash
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#          NPM_CONFIG_PROVENANCE: true
