name: CI

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  PNPM_VERSION: latest

permissions:
  actions: read
  contents: read

jobs:
  commit_lint:
    name: Validate commit messages
    runs-on: ${{ vars.DEFAULT_RUNNER || 'ubuntu-latest'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node and pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install commitlint
        run: |
          pnpm add conventional-changelog-conventionalcommits
          pnpm add commitlint@latest

      - name: Validate last commit
        if: github.event_name == 'push'
        run: pnpm exec commitlint --last --verbose

      - name: Validate PR commits
        if: github.event_name == 'pull_request'
        run: pnpm exec commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

  code_quality:
    name: Run code quality tests
    runs-on: ${{ vars.DEFAULT_RUNNER || 'ubuntu-latest'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Connect your workspace on nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
      # - run: pnpm exec nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="e2e-ci"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node and pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup SHAs
        uses: stetind/web-github-composite-actions/setup-shas@v1

      - name: Run linter
        run: pnpm exec nx affected -t lint

      - name: Run stylelint
        run: pnpm exec nx affected -t stylelint

      - name: Run formatting
        run: pnpm exec nx format:check

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: pnpm exec nx-cloud record -- echo Hello World
      # - run: pnpm exec nx affected -t lint test build
      # run: pnpm exec nx affected --parallel 1 -t e2e-ci

  unit_tests:
    name: Run unit tests
    runs-on: ${{ vars.DEFAULT_RUNNER || 'ubuntu-latest'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node and pnpm cache
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup SHAs
        uses: stetind/web-github-composite-actions/setup-shas@v1

      - name: Run tests
        run: pnpm exec nx affected -t test
